#!/bin/bash
#SBATCH --job-name=HSpend
#SBATCH -A AST25019
#SBATCH --nodes=1
#SBATCH -p gh-dev
#SBATCH --time=1:00:00


accelerate launch  train_hetdex.py /scratch/06536/qezlou/hetdex/data/ /scratch/06536/qezlou/hetdex/data/models/out.pt -v -b 1024 -e 2
