#!/bin/bash
#SBATCH -A AST25019
#SBATCH -J cov
#SBATCH -p development 
#SBATCH -N 1
#SBATCH --ntasks-per-node 1
#SBATCH --time=2:00:00
#SBATCH --output=%x-%j.out

hostname; pwd; date

python get_cov.py
